name: list out the default env for the different OS
on:
  workflow_dispatch:

jobs:
  windows_default_env:
    runs-on: windows-latest
    steps:
    - name: P
      run: env


  macOS_default_env:
    runs-on: macos-latest
    steps:
    - name: A
      run: env