name: first workflow project
on:
  push:
    branches: ["master"]
jobs:
  build_release:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo "jesus is lord "
    - name: echo a multiline
      run: | 
        echo "come to jesus and be safe"
        echo "He is the only way "