name: step_by_step
on: 
  workflow_dispatch:

jobs:
  step_deployment:
    runs-on: windows-latest
    steps:
      - name: create a variable and append
        run: |
          echo "value=it-works >> $GITHUB_ENV
      
      
      - name: create some variables
        id: pointer_variables
        run: | 
          echo "just perform this random task"
          echo "::set-output name=var1_name ::peter"
      


      - name: get the variables 
        run: |
          echo "value : ${{env.value}}"
          echo "instep variable : ${{steps.pointer_variables.outputs.var1_name}}"
