name: secretfile
on:
  workflow_dispatch:

jobs:
  my_secret:
    runs-on: ubuntu-latest
    steps:
    - name: print out secret
      run:  |
        echo "MY_TOP_SEC : ${{secrets.MY_TOP_SEC}}"
        echo "MY_TOP_SEC: ${{secrets.i_dont_exist}}"
    - name: print from within
      run: |
        echo "my_top_secret: env.my_key"
      env:
        my_key : ${{secrets.MY_TOP_SEC}}