name: secretfile
on:
  workflow_dispatch:

jobs:
  my_secret:
    runs-on: ubuntu-latest
    steps:
    - name: print out secrete
      run: |
        echo "MY_TOP_SEC : ${{secrets.MY_TOP_SEC}}"
        echo "MY_TOP_SEC: ${{secrets.i_don't_exist}}"